### ISSUE TITLE
Registration fails, when pin start with a 0

### ISSUE THREAD

**Issue by nanu-c** [whisperfish/presage#108]
`confirm_verification_code` https://github.com/whisperfish/presage/blob/main/src/manager.rs#L373 should use a `string` instead of a `u32` because when the code is `001234` then the first 2 digits are dropped.

The bug is inherited from libsignal-service-rs 
https://github.com/whisperfish/libsignal-service-rs/blob/main/libsignal-service/src/provisioning/manager.rs#L173

**Comment by gferon** [comment]
Fixed in https://github.com/whisperfish/libsignal-service-rs/pull/201
