### ISSUE TITLE
Detection of changed safety number

### ISSUE THREAD

**Issue by langfingaz** [whisperfish/presage#181]
Hi, I'm a user of Flare which uses this library. Many thanks for creating it!

If a user installs installs their main Signal client on a new phone (or re-installs it on the same phone), the official Signal clients display this message in chats with that person:

> Your safety number with ... has changed. **Learn more.**

Do you know, if it is already possible to detect a changed safety number of a user with `presage` without sending a message to that user?

This would enable applications such as Flare to inform users about changed safety numbers of chat opponents. At the moment, Flare displays an error when trying to send a message in that case (ProtocolError, UntrustedIdentity) - so this is already better than silently ignoring changed security keys completely, but definitely not ideal ;)

**Comment by gferon** [comment]
I believe this was addressed in https://github.com/whisperfish/presage/pull/206
