### ISSUE TITLE
MessagePipeNotStarted when trying to send to group

### ISSUE THREAD

**Issue by yazgoo** [whisperfish/presage#198]
Hi, I cannot send message to groups 	

```
❯ cargo run -- list-groups
<group_id> Name: None / revision 7 / 4 members
```

```
❯ cargo run -- send-to-group --message message --master-key <group_id>`
Error: message pipe not started, you need to start receiving messages before you can send anything back
```

**Comment by gferon** [comment]
Fixed in https://github.com/whisperfish/presage/pull/210

**Comment by yazgoo** [comment]
I confirm that it works on my end !

Thanks a lot !

**Comment by gferon** [comment]
> Great project by the way ❤️

Thanks a lot, feel free to [drop by in the Matrix channel](https://matrix.to/#/#presage:rubdos.be) if you have questions or issues!
