### ISSUE TITLE
Message sending hangs, message not visible on some devices afterwards.

### ISSUE THREAD

**Issue by k-bx** [whisperfish/presage#200]
Might be two separate issues to resolve. Sending message to a group is hanging, so I have to wrap my `manager.send_message_to_group` in a `tokio::time::timeout`. The message is still sent, it's visible by other group members, and it's visible on Signal Android app, but not visible on Signal Desktop apps.

What's the best way to investigate this issue? Does the "not visible on Desktop client" part even make sense? Feels very bizzare to me.

**Comment by k-bx** [comment]
For context: Desktop signal is showing this error:

<img width="468" alt="Знімок екрана 2023-10-21 о 12 44 32" src="https://github.com/whisperfish/presage/assets/107968/4e0a5302-6e7b-49dd-b6b4-ccd28afaef91">

It's in Ukrainian so here's the translation:

Title: Problem with Delivery
Body: Couldn't deliver a message, sticker, reaction, media or read notification from user XXX to you. Maybe, the user sent this directly to you or in a group.

**Comment by gferon** [comment]
Thanks for the report! I'll look into it. It might be related to the need to sync first before being able to send.
