### ISSUE TITLE
Refresh QR code when linking takes too long

### ISSUE THREAD

**Issue by Schmiddiii** [whisperfish/presage#217]
Currently, if the user is not able to scan the QR (or more generally, a provisioning link) code quick enough (I think Signal has a timeout of about 1 minute for this action), presage throws a `NoProvisioningReceived`-error. Ideally, it would restart the process and generate another provisioning link to send over the `provisioning_link_channel`.

**Comment by gferon** [comment]
This is now fixed with https://github.com/whisperfish/libsignal-service-rs/pull/269 since the provisioning websocket has keep-alive enabled.
