### ISSUE TITLE
Request: Java bindings

### ISSUE THREAD

**Issue by The-Ladle** [whisperfish/presage#265]
I want to make my own android client for signal, but sadly, libsignal-service-java appears to be deprecated. Therefore, I searched further, and came across this. Sadly, this only has rust support. Could java bindings be made?

**Comment by gferon** [comment]
I have no experience with exposing Java bindings from Rust but have done C-bindings in the past. I'm not super it would make a lot of sense and you might have better luck trying to use the official libsignal and build around that?
