### ISSUE TITLE
Making the future returned by get_attachment Send?

### ISSUE THREAD

**Issue by nicohman** [whisperfish/presage#32]
Hi, I was just wondering if there was any possible way to make the future returned by Manager::get_attachment `Send`, so that attachments can be downloaded in separate threads to avoid blocking.

**Comment by gferon** [comment]
Better now than never: is this still a problem for you? I think it'd have to be looked at upstream in `libsignal-service-rs`.

**Comment by gferon** [comment]
I think I can close this now, `get_attachment` shouldn't block in any way as it's fully `async`. If you really need to `Send` it to another thread, you can always clone the `Manager`.
