### ISSUE TITLE
Example cli usage of captcha unclear

### ISSUE THREAD

**Issue by maltevesper** [whisperfish/presage#39]
I tried registering a new device, unfortunately I am not sure what exactly is expected for the `--captcha` flag. I went to https://signalcaptchas.org/registration/generate.html, and solved the captcha, I then looked at the devconsole and saw something like this:

![image](https://user-images.githubusercontent.com/10866845/147410468-a774efaa-89a3-4bbc-8973-8eb32cde44a2.png)

I assumed that the address is the captcha, however when I use it in one of the variations below (with _signalcaptcha://_ protokoll and without), I always get the error "_Error: this client is already registered with Signal_".

`cargo run --example=cli -- register --phone-number +49<XXX> --use-voice-call --captcha 'signalcaptcha://03AGdBq26_isUvEyO8j-UR2treKfupr7j9RB1ZZqTwoPcA....na-GXbhBw'` 
`cargo run --example=cli -- register --phone-number +49<XXX> --use-voice-call --captcha '03AGdBq26_isUvEyO8j-UR2treKfupr7j9RB1ZZqTwoPcA....na-GXbhBw'` 

Am I doing something wrong (what am I supposed to pass to --captcha), or is this a bug?

**Comment by ivan** [comment]
(I am trying to figure this out as well.) `--force` seemed to resolve "Error: this client is already registered with Signal" for me.

```
cargo run --example=cli -- register --servers production --force --phone-number PHONE --captcha CAPTCHA
```

It looks like it wants the CAPTCHA without the `signalcaptcha://`.

I was unable to proceed anyway because of

```
# presage-cli verify --confirmation-code 849282
Error: libsignal-service error: Unexpected response: HTTP 422

Caused by:
    Unexpected response: HTTP 422
```

**Comment by gferon** [comment]
Thanks for reporting the issue and sorry for not answering earlier!

I got a fix and will try to get it merge in the next few days.
