### ISSUE TITLE
Example cli send broken

### ISSUE THREAD

**Issue by maltevesper** [whisperfish/presage#40]
```
cargo run --example=cli -- send --message "ok bob" --phone-number +<countrycode><actualphonenumber without leading 0>

Error: libsignal-service sending error: Unexpected response: HTTP 404

Caused by:
    0: Unexpected response: HTTP 404
    1: Unexpected response: HTTP 404
```

I would assume that this issue is not necessarily limited to the example cli.

**Comment by gferon** [comment]
This is because Signal has dropped any API calls that use the phone-number. This is fixed after merging https://github.com/whisperfish/presage/pull/37. I'll try to come up with a way to restore the functionality on the client-side, since we store contacts.
