### ISSUE TITLE
Local Encryption / Filesystem Sync

### ISSUE THREAD

**Issue by Philipp-Sc** [whisperfish/presage#50]
Hey there,

first of all, thank you for working on this awesome project!

I am want to use presage as part of my terra-rust-bot to send notifications and to reply to messages.
The only thing I am concerned about is that in case the system is compromised the signal account is not protected. (Encrypted storage #23)
I want to prevent someone else to use the linked device / account and optimally protect the chat history as well.

I would like not to store anything on the filesystem and have the bot save all the information it needs in working memory.
Using:

- https://github.com/unrelentingtech/secstr
- https://github.com/anvie/litcrypt.rs

It looks like the config_store saves everything to the file system.
`let config_store = SledConfigStore::new(db_path)?; `

Can you point me to the parts of the code I need to change so that the config_store is only used in memory? (from what I read about Sled it fsyncs every 500 ms.)
If you have any other insights I am happy to hear them as well.

Best regards,
Philipp

**Comment by Philipp-Sc** [comment]
I found this

https://github.com/jpopesculian/encrypted-sled

is there any reason why this would not work with presage?

**Comment by gferon** [comment]
I think the best way to achieve your goal would be to completely implement a in-memory storage. I can implement one rather quickly, but I first need to ask: do you need any form of limited storage (in the sense that you should never grow infinitely), or do you just want to have all of the storage in volatile memory.

As for `encrypted-sled`, I'll give it a closer look.

**Comment by Philipp-Sc** [comment]
Regarding the storage of messages, contacts and similar information. I do not need/want them to be stored.

Regarding my bot: 
The messages are only read once when they arrive and then never used again.

I modified presage here: https://github.com/whisperfish/presage/compare/main...Philipp-Sc:main
I hope the code I out-commented in [src/manager.rs](https://github.com/whisperfish/presage/compare/main...Philipp-Sc:main#diff-7143adb2b6aaf4eac74de6b133c6a9cf6d2d34bf6929972361f93100abdfc074) results in the messages not being saved.

I think putting the `ConfigStore` in-memory would be a good solution. It would be awesome if there also was a function to export/import the `ConfigStore` so users do not need to re-link their device every time they restart the bot.

**Comment by gferon** [comment]
`presage` doesn't store messages at all (it might with an opt-in feature in the future if I work on #44) so that's a non-issue for you 😄 

I can add a in-memory implementation of the `ConfigStore` trait but I feel that if you want import/export from disk it really defeats the purpose... maybe you simply could create a directory in a tmpfs (`/tmp` usually is on most Linux distributions) with restricted permissions and use that for `sled`?

As for saving contacts, I could introduce a configuration flag somewhere to skip those messages, WDYT?

**Comment by Philipp-Sc** [comment]
not sure what I out-commented, but it didn't stop presage from working well.

yeah you are right, having import/export makes no sense. 
I think it's best to go with max. security. It might be inconvenient to re-link a device, after restarting the bot, but it is important nobody can take over the signal message pipeline. 

So a in-memory solution for the `ConfigStore` would be awesome. 
Regarding the **contacts saving** an on/off switch would also be great, but no priority for me as I just out-commented that part of the code. Thank you for working on this.

Best regards,
Philipp

**Comment by Philipp-Sc** [comment]
@gferon I think for my use case that is fine/perfect. I use presage as a notification bot only for the users account, no other accounts are allowed to interact with the bot. I check that the UUID equals the UUID from `manager.whoami()`.

**Comment by Philipp-Sc** [comment]
@gferon thanks a lot for implementing this.

While experts still can inspect the memory, this makes it safer from a practical perspective.
Also with the new `volatile.rs` code it's easier to understand how presage works.

**Comment by Philipp-Sc** [comment]
@herrsimon what speaks against using https://github.com/stouset/secrets in addition?

**Comment by Philipp-Sc** [comment]
@gferon I think I should be able to add the above crate to the `VolatileConfigStore` struct.

Basically only need to wrap the types `u32` and `Vec<u8>` within `SecretBox` and `SecretVec` and adjust the functions a little. Just want to check here first if this makes sense.

Let me know what you think.

**Comment by gferon** [comment]
Sure, sounds good. If you add the crate, can you put it and the volatile store behind a feature flag? Thanks!

**Comment by Philipp-Sc** [comment]
#60 for reference
