### ISSUE TITLE
CLI send-to-group does not work

### ISSUE THREAD

**Issue by Schmiddiii** [whisperfish/presage#64]
Currently the send-to-group of the CLI does not work. It seems that sending using PhoneNumbers is deprecated and one should send using the UUID. For more information, see the Whisperfish Signal group chat.

I may try to fix that myself and make a PR as I need this to try to replicate another bug I am having.

**Comment by gferon** [comment]
Interesting, i must have lost this change in the last refactor I did. We should actually remove `e164` fields from our libs altogether.

I'm on vacation for the next 10 days and can have a look when I'm back!
