### ISSUE TITLE
[feature request] Release on crates.io

### ISSUE THREAD

**Issue by werdahias** [whisperfish/presage#75]
Could you please release this crate on crates.io? I intend to package it for debian; for this it has to be on crates.io

Cheers

**Comment by gferon** [comment]
Until https://github.com/signalapp/libsignal/issues/490 gets some traction, there's nothing we can do here.

**Comment by gferon** [comment]
I'll close this issue for now, as we know we won't be able to move forward without `libsignal` and a newer `curve25519-dalek` on crates.io
