### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Schmiddiii** [whisperfish/presage#76]
Here is a list of feature requests that might fit good into presage as most clients building upon that may want such features. I will not be able to work on any of those features in the next few months, and do not expect any of you to work on it if you don' t want to:

- ~~Clearing messages without clearing other data~~
- Group Storage similar to `request_contacts_sync` and `get_contacts`
- Encrypted attachment storage
- Last-read/received message by `Thread` and `Contact`
- Query reactions by message
- Handle delete-messages
- Wrapper for stores: When implementing all of those above options, some clients may want to turn some things off. I would therefore make a light wrapper around any generic store that has a builder to en- or disable features and depending on if those features are en- or disabled, either proxy the method to the underlying store or return defaults.

**Comment by gferon** [comment]
I'll close this issue, as I believe we managed to either deal with some of them and extract the rest into separate issues.
