### ISSUE TITLE
Push support via UnifiedPush

### ISSUE THREAD

**Issue by darkdragon-001** [whisperfish/presage#90]
Would this library be the right place to implement push support via [UnifiedPush](https://unifiedpush.org/) specification (for Whisperfish, Axolotl, ...)?

Blocked by UnifiedPush/wishlist#8

**Comment by gferon** [comment]
Well, `whisperfish` uses its own back end implementation for [libsignal-service-rs](https://github.com/whisperfish/libsignal-service-rs). I know of a few other that use this project, and AFAIK Axolotl will (or is?) using `presage` already (@nanu-c correct me if I'm wrong.)

I believe we could give this a shot as an optional feature in here?

**Comment by Schmiddiii** [comment]
As far as I understood UnifiedPush, for any Signal-clients to support it there must first be support on the Signal servers (see also the video in the getting-started section of UnifiedPush, it always also shows a server interacting with UnifiedPush). As this is currently not implemented (at least as far as I know), this is impossible for any Signal clients (even the official ones).

Related issue in Flare: <https://gitlab.com/Schmiddiii/flare/-/issues/36>.

**Comment by nanu-c** [comment]
Actually it's possible via a bridge: https://github.com/MollySocket/mollysocket

**Comment by gferon** [comment]
Closing since this is not really we can implement only on the client-side.

**Comment by darkdragon-001** [comment]
@gferon can't we just use the Molly bridge in the client?
