### ISSUE TITLE
Don't save every message to the store.

### ISSUE THREAD

**Issue by nanu-c** [whisperfish/presage#95]
Currently, every sync message is saved to the store. But that's not necessary, can we make a list for what is relevant and what not?
![grafik](https://user-images.githubusercontent.com/404058/213387712-e039ecc8-c7eb-4657-ae24-4e72fe4d9ad5.png)

**Comment by gferon** [comment]
The problem here is that it is rather dependent of the usage you make of these messages in the client. I'm not sure there's a good way to do that at the moment.

**Comment by nanu-c** [comment]
In the client i would listen to the message queue in order to handle the read messages. So no need to save the read message for example. Or the key update message should be handled by pressage and then dropped. So it depends ;)

**Comment by gferon** [comment]
This is giving me an idea, what do you think about being able to control what's saved or not from the received message loop? I'm thinking of rewriting it to be like a small state machine, which would make it much cleaner and powerful.
