### ISSUE TITLE
Sending messages broke

### ISSUE THREAD

**Issue by boxdot** [whisperfish/presage#96]
After intializing manager and starting listening to it, sending does not work:

```
2023-01-20T08:41:46.470559Z ERROR gurk::signal::r#impl: Failed to send message to 779a6c6b-0985-479a-86fc-ce435a3db130: message pipe not started, you need to start receiving messages before you can send anything back
```

I see in the logs, that there is a connection to the websocket though. Maybe cloning the manager does not share the state?

**Comment by gferon** [comment]
Interesting, I only tested the initial registration which sends messages, you're probably right.

**Comment by boxdot** [comment]
Ah, of course. The `State` is just cloned. It is not shared between the managers.

**Comment by gferon** [comment]
Thanks for finding this out, I must admit I committed a bit in a hurry before leaving for vacation 😅
