### ISSUE TITLE
Handle UntrustedIdentity

### ISSUE THREAD

**Issue by Schmiddiii** [whisperfish/presage#99]
As discussed in the Whisperfish Matrix room, `presage` should probably catch that error and send a identity-reset message.

Related error in Flare: <https://gitlab.com/Schmiddiii/flare/-/issues/43>.

**Comment by gferon** [comment]
So, you really want to catch this in your UI to let users do what they think is best, because this effectively means the person in front of you might have changed identity. I'll expose a method to be able to perform the reset operation yourself.
